language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t 09092013/react-test -f ./client/Dockerfile.dev ./client
  
#script:
#  - docker run -e CI=true 09092013/react-test npm run test

#create images for all projects   
after_success:
  - docker build -t 09092013/multi-client ./client
  - docker build -t 09092013/multi-nginx ./nginx
  - docker build -t 09092013/multi-server ./server
  - docker build -t 09092013/multi-worker ./worker
  
# Login to docker CLI, login credentials set up as env variables in Travis in multi-docker repo
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io
 
# push images to docker hub, first create these repos in hub.docker.com for your user id, then this push command will work
  - docker push 09092013/multi-client
  - docker push 09092013/multi-nginx
  - docker push 09092013/multi-server
  - docker push 09092013/multi-worker
  
deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multidocker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-543764981007"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY